### ISSUE TITLE
give path to os.listdir()

### ISSUE THREAD

**Issue by diveshuttam** [diveshuttam/termicoder#7]
in python 2 `os.listdir()` doesn't default to current directory. have a look

**Comment by svaderia** [comment]
Give `os.getcwd()` as argument to `os.llistdir()`.
`os.getcwd()` is equlient of `pwd` in terminal.

**Comment by diveshuttam** [comment]
know of os.getcwd() approach. have used it at a couple of places. I was using for may be something like `os.listdir(".")` though it works on linux... don't know about windows
